"""水印检测模块 – WatermarkDetector

Blind (reference-free) watermark detection via correlation against
the keyed PN sequences generated by :class:`WatermarkEncoder`.

For each embedding frame the detector computes the dot product between
the (possibly attacked) frame and the expected PN sequence.  The sign of
this correlation gives the hard bit decision; its magnitude is the soft
confidence.

The recovered bit decisions are passed to :meth:`WatermarkEncoder.decode`
which applies majority voting and CRC verification.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Optional, Tuple

import numpy as np

from .watermark_encoder import WatermarkEncoder


@dataclass
class DetectionResult:
    """Result returned by :meth:`WatermarkDetector.detect`.

    Attributes
    ----------
    detected : bool
        True when the CRC check passes and a valid message was recovered.
    message : str
        Decoded message (empty string on failure).
    confidence : float
        Mean absolute correlation across all recovered frames (0–1 scale).
    n_frames_used : int
        Number of embedding frames read from the audio.
    bit_stream : np.ndarray
        Hard bit decisions (shape: n_frames_used,).
    soft_decisions : np.ndarray
        Normalised correlation values (shape: n_frames_used,).
    """

    detected: bool = False
    message: str = ""
    confidence: float = 0.0
    n_frames_used: int = 0
    bit_stream: np.ndarray = field(default_factory=lambda: np.array([], dtype=np.uint8))
    soft_decisions: np.ndarray = field(default_factory=lambda: np.array([], dtype=np.float32))


class WatermarkDetector:
    """Detect and decode a spread-spectrum watermark from audio.

    Parameters
    ----------
    encoder : WatermarkEncoder
        Must use the *same* key and repeat factor as the embedder.
    frame_length : int
        Must match the frame length used during embedding.
    """

    def __init__(
        self,
        encoder: Optional[WatermarkEncoder] = None,
        frame_length: int = 256,
    ) -> None:
        self.encoder = encoder or WatermarkEncoder()
        self.frame_length = frame_length

    def detect(self, audio: np.ndarray, n_bits: Optional[int] = None) -> DetectionResult:
        """Attempt to recover the watermark embedded in *audio*.

        The detector reads up to *n_bits* frames (or as many as possible).
        It then calls :meth:`WatermarkEncoder.decode` to recover the message.

        Parameters
        ----------
        audio : np.ndarray, shape (N,)
            Possibly attacked mono audio.
        n_bits : int, optional
            Expected total number of bits in the encoded stream (after
            repetition).  When None the detector reads all available frames.

        Returns
        -------
        result : DetectionResult
        """
        audio = np.asarray(audio, dtype=np.float32)
        L = self.frame_length
        n_frames_available = len(audio) // L
        n_frames = n_frames_available if n_bits is None else min(n_bits, n_frames_available)

        if n_frames == 0:
            return DetectionResult()

        soft = np.zeros(n_frames, dtype=np.float32)
        hard = np.zeros(n_frames, dtype=np.uint8)

        for i in range(n_frames):
            frame = audio[i * L : (i + 1) * L]
            pn = self.encoder.generate_pn(i, L)
            # Normalised correlation
            corr = float(np.dot(frame, pn)) / (L + 1e-9)
            soft[i] = corr
            hard[i] = 1 if corr >= 0 else 0

        message, valid = self.encoder.decode(hard)
        confidence = float(np.mean(np.abs(soft)))

        return DetectionResult(
            detected=valid,
            message=message,
            confidence=confidence,
            n_frames_used=n_frames,
            bit_stream=hard,
            soft_decisions=soft,
        )

    def compute_ber(
        self,
        original_bits: np.ndarray,
        recovered_bits: np.ndarray,
    ) -> float:
        """Compute Bit Error Rate between two bit arrays.

        Parameters
        ----------
        original_bits : np.ndarray
        recovered_bits : np.ndarray

        Returns
        -------
        ber : float in [0, 1]
        """
        n = min(len(original_bits), len(recovered_bits))
        if n == 0:
            return 1.0
        errors = int(np.sum(original_bits[:n] != recovered_bits[:n]))
        return errors / n
